import type { QuestionTypeSeed } from "./types";

export const QUESTION_TYPE_SEEDS: Record<string, QuestionTypeSeed> = {
  mcqSingle: {
    slug: "mcqSingle",
    name: "MCQ (Single Answer)",
    category: "selection",
    responseFormat: "single_choice",
    answerFormat: "singleOptionSelection",
    hasAudio: false,
    hasImage: false,
    hasPassage: false,
    autoScorable: true,
  },
  mcqMultiple: {
    slug: "mcqMultiple",
    name: "MCQ (Multiple Answers)",
    category: "selection",
    responseFormat: "multi_choice",
    answerFormat: "multiOptionSelection",
    hasAudio: false,
    hasImage: false,
    hasPassage: false,
    autoScorable: true,
  },
  dragAndDropFill: {
    slug: "dragAndDropFill",
    name: "Fill in the Blanks — Drag & Drop",
    category: "selection",
    responseFormat: "fill_blank_drag_drop",
    answerFormat: "slotFillSelection",
    hasAudio: false,
    hasImage: false,
    hasPassage: true,
    autoScorable: true,
  },
  dropdownFill: {
    slug: "dropdownFill",
    name: "Fill in the Blanks — Drop Down",
    category: "selection",
    responseFormat: "fill_blank_dropdown",
    answerFormat: "slotFillSelection",
    hasAudio: false,
    hasImage: false,
    hasPassage: true,
    autoScorable: true,
  },
  matchTheFollowing: {
    slug: "matchTheFollowing",
    name: "Match the Following",
    category: "selection",
    responseFormat: "matching",
    answerFormat: "matchPairSelection",
    hasAudio: false,
    hasImage: false,
    hasPassage: false,
    autoScorable: true,
  },
  essay: {
    slug: "essay",
    name: "Writing Essay",
    category: "textInput",
    responseFormat: "text_response",
    answerFormat: "freeText",
    hasAudio: false,
    hasImage: false,
    hasPassage: true,
    autoScorable: false,
  },
  textSummary: {
    slug: "textSummary",
    name: "Summary",
    category: "textInput",
    responseFormat: "text_response",
    answerFormat: "freeText",
    hasAudio: false,
    hasImage: false,
    hasPassage: true,
    autoScorable: false,
  },
  email: {
    slug: "email",
    name: "Email",
    category: "textInput",
    responseFormat: "text_response",
    answerFormat: "freeText",
    hasAudio: false,
    hasImage: false,
    hasPassage: true,
    autoScorable: false,
  },
  letter: {
    slug: "letter",
    name: "Letter Writing",
    category: "textInput",
    responseFormat: "text_response",
    answerFormat: "freeText",
    hasAudio: false,
    hasImage: false,
    hasPassage: true,
    autoScorable: false,
  },
  notice: {
    slug: "notice",
    name: "Notice Writing",
    category: "textInput",
    responseFormat: "text_response",
    answerFormat: "freeText",
    hasAudio: false,
    hasImage: false,
    hasPassage: true,
    autoScorable: false,
  },
  dialogueCompletion: {
    slug: "dialogueCompletion",
    name: "Dialogue Completion",
    category: "textInput",
    responseFormat: "text_response",
    answerFormat: "freeText",
    hasAudio: false,
    hasImage: false,
    hasPassage: true,
    autoScorable: false,
  },
  summarizeSpokenText: {
    slug: "summarizeSpokenText",
    name: "Summarize Spoken Text",
    category: "audioListening",
    responseFormat: "text_response",
    answerFormat: "freeText",
    hasAudio: true,
    hasImage: false,
    hasPassage: false,
    autoScorable: false,
  },
  audioMcqMultiple: {
    slug: "audioMcqMultiple",
    name: "Audio MCQ (Multiple Answers)",
    category: "audioListening",
    responseFormat: "multi_choice",
    answerFormat: "multiOptionSelection",
    hasAudio: true,
    hasImage: false,
    hasPassage: false,
    autoScorable: true,
  },
  audioDropdownFill: {
    slug: "audioDropdownFill",
    name: "Audio Fill in the Blanks — Drop Down",
    category: "audioListening",
    responseFormat: "fill_blank_dropdown",
    answerFormat: "slotFillSelection",
    hasAudio: true,
    hasImage: false,
    hasPassage: true,
    autoScorable: true,
  },
  audioDragAndDropFill: {
    slug: "audioDragAndDropFill",
    name: "Audio Fill in the Blanks — Drag & Drop",
    category: "audioListening",
    responseFormat: "fill_blank_drag_drop",
    answerFormat: "slotFillSelection",
    hasAudio: true,
    hasImage: false,
    hasPassage: true,
    autoScorable: true,
  },
  audioBestOption: {
    slug: "audioBestOption",
    name: "Audio Best-Matching Option",
    category: "audioListening",
    responseFormat: "single_choice",
    answerFormat: "singleOptionSelection",
    hasAudio: true,
    hasImage: false,
    hasPassage: false,
    autoScorable: true,
  },
  audioMcqSingle: {
    slug: "audioMcqSingle",
    name: "Audio MCQ (Single Answer)",
    category: "audioListening",
    responseFormat: "single_choice",
    answerFormat: "singleOptionSelection",
    hasAudio: true,
    hasImage: false,
    hasPassage: false,
    autoScorable: true,
  },
  highlightWords: {
    slug: "highlightWords",
    name: "Highlight Incorrect Words",
    category: "visualHighlight",
    responseFormat: "word_highlight",
    answerFormat: "wordHighlightSelection",
    hasAudio: false,
    hasImage: false,
    hasPassage: true,
    autoScorable: true,
  },
  audioSpeakingResponse: {
    slug: "audioSpeakingResponse",
    name: "Audio Speaking Response",
    category: "audioSpeaking",
    responseFormat: "audio_response",
    answerFormat: "audioRecording",
    hasAudio: true,
    hasImage: false,
    hasPassage: false,
    autoScorable: false,
  },
  repeatSentence: {
    slug: "repeatSentence",
    name: "Repeat Sentence",
    category: "audioSpeaking",
    responseFormat: "audio_response",
    answerFormat: "audioRecording",
    hasAudio: true,
    hasImage: false,
    hasPassage: false,
    autoScorable: false,
  },
  readAloud: {
    slug: "readAloud",
    name: "Read Aloud",
    category: "audioSpeaking",
    responseFormat: "audio_response",
    answerFormat: "audioRecording",
    hasAudio: false,
    hasImage: false,
    hasPassage: true,
    autoScorable: false,
  },
  dataInterpretation: {
    slug: "dataInterpretation",
    name: "Data Interpretation",
    category: "visualImage",
    responseFormat: "text_response",
    answerFormat: "freeText",
    hasAudio: false,
    hasImage: true,
    hasPassage: false,
    autoScorable: false,
  },
  describeImage: {
    slug: "describeImage",
    name: "Describe Image",
    category: "visualImage",
    responseFormat: "audio_response",
    answerFormat: "audioRecording",
    hasAudio: false,
    hasImage: true,
    hasPassage: false,
    autoScorable: false,
  },
};
