import type { SectionSeedEntry } from "./types";

export const VERBAL_COMMUNICATION: SectionSeedEntry = {
  section: {
    slug: "verbal-communication",
    name: "Verbal Communication",
    description:
      "Assesses spoken and comprehension skills through audio, image, and situational prompts.",
    isCoreSection: true,
  },
  questionTypes: [
    {
      slug: "audio-comprehension",
      name: "Audio Comprehension",
      category: "verbal",
      responseFormat: "audio_response",
      hasAudio: true,
      hasImage: false,
      hasPassage: false,
      autoScorable: false,
    },
    {
      slug: "repeat-sentence",
      name: "Repeat Sentence",
      category: "verbal",
      responseFormat: "audio_response",
      hasAudio: true,
      hasImage: false,
      hasPassage: false,
      autoScorable: false,
    },
    {
      slug: "read-aloud",
      name: "Read Aloud",
      category: "verbal",
      responseFormat: "audio_response",
      hasAudio: false,
      hasImage: false,
      hasPassage: true,
      autoScorable: false,
    },
    {
      slug: "respond-to-a-situation",
      name: "Respond to a Situation",
      category: "verbal",
      responseFormat: "audio_response",
      hasAudio: false,
      hasImage: false,
      hasPassage: true,
      autoScorable: false,
    },
    {
      slug: "describe-image",
      name: "Describe Image",
      category: "verbal",
      responseFormat: "audio_response",
      hasAudio: false,
      hasImage: true,
      hasPassage: false,
      autoScorable: false,
    },
    {
      slug: "voice-response",
      name: "Voice Response",
      category: "verbal",
      responseFormat: "audio_response",
      hasAudio: false,
      hasImage: false,
      hasPassage: true,
      autoScorable: false,
    },
    // Voice-input variants of the choice/fill-blank formats used elsewhere
    // (Aptitude, Listening & Reading) — same content shape (options/blanks),
    // but the student answers by recording audio instead of picking a
    // value, so none of these are auto-scorable.
    {
      slug: "voice-mcq",
      name: "Voice MCQ",
      category: "verbal",
      responseFormat: "voice_mcq",
      hasAudio: true,
      hasImage: false,
      hasPassage: false,
      autoScorable: false,
    },
    {
      slug: "voice-dropdown",
      name: "Voice Dropdown",
      category: "verbal",
      responseFormat: "voice_dropdown",
      hasAudio: true,
      hasImage: false,
      hasPassage: true,
      autoScorable: false,
    },
    {
      slug: "voice-fill-blank",
      name: "Voice Filling Blank",
      category: "verbal",
      responseFormat: "voice_fill_blank",
      hasAudio: true,
      hasImage: false,
      hasPassage: true,
      autoScorable: false,
    },
    {
      slug: "voice-incorrect-words",
      name: "Voice Incorrect Words",
      category: "verbal",
      responseFormat: "voice_incorrect_words",
      hasAudio: false,
      hasImage: false,
      hasPassage: true,
      autoScorable: false,
    },
  ],
};
