import type { SectionSeedEntry } from "./types";

export const WRITTEN_COMMUNICATION: SectionSeedEntry = {
  section: {
    slug: "written-communication",
    name: "Written Communication",
    description:
      "Evaluates written expression through essays, professional writing, and structured compositions.",
    isCoreSection: true,
  },
  questionTypes: [
    {
      slug: "writing-essay",
      name: "Writing Essay",
      category: "written",
      responseFormat: "text_response",
      hasAudio: false,
      hasImage: false,
      hasPassage: true,
      autoScorable: false,
    },
    {
      slug: "summary-writing",
      name: "Summary",
      category: "written",
      responseFormat: "text_response",
      hasAudio: false,
      hasImage: false,
      hasPassage: true,
      autoScorable: false,
    },
    {
      slug: "email-writing",
      name: "Email",
      category: "written",
      responseFormat: "text_response",
      hasAudio: false,
      hasImage: false,
      hasPassage: true,
      autoScorable: false,
    },
    {
      slug: "describe-image-writing",
      name: "Describe Image",
      category: "written",
      responseFormat: "text_response",
      hasAudio: false,
      hasImage: true,
      hasPassage: false,
      autoScorable: false,
    },
    {
      slug: "letter-writing",
      name: "Letter Writing",
      category: "written",
      responseFormat: "text_response",
      hasAudio: false,
      hasImage: false,
      hasPassage: true,
      autoScorable: false,
    },
    {
      slug: "notice-writing",
      name: "Notice Writing",
      category: "written",
      responseFormat: "text_response",
      hasAudio: false,
      hasImage: false,
      hasPassage: true,
      autoScorable: false,
    },
    {
      slug: "dialog-writing",
      name: "Dialog Writing",
      category: "written",
      responseFormat: "text_response",
      hasAudio: false,
      hasImage: false,
      hasPassage: true,
      autoScorable: false,
    },
  ],
};
