export const BLINK_ROLES = {
  ASSOCIATE_ADMIN: 'associate_admin',
  ASSOCIATE_EMPLOYEE: 'associate_employee',
  CAMPUS_AMBASSADOR: 'campus_ambassador',
}

export const BLINK_PERMISSIONS = {
  DASHBOARD_VIEW: 'blink:dashboard:view',
  REFERRALS_MANAGE: 'blink:referrals:manage',
  COMMISSIONS_VIEW: 'blink:commissions:view',
  TEAM_MANAGE: 'blink:team:manage',
  PROFILE_VIEW: 'blink:profile:view',
}

export const BLINK_ROLE_PERMISSIONS: Record<string, string[]> = {
  [BLINK_ROLES.ASSOCIATE_ADMIN]: [
    BLINK_PERMISSIONS.DASHBOARD_VIEW,
    BLINK_PERMISSIONS.REFERRALS_MANAGE,
    BLINK_PERMISSIONS.COMMISSIONS_VIEW,
    BLINK_PERMISSIONS.TEAM_MANAGE,
    BLINK_PERMISSIONS.PROFILE_VIEW,
  ],
  [BLINK_ROLES.ASSOCIATE_EMPLOYEE]: [
    BLINK_PERMISSIONS.DASHBOARD_VIEW,
    BLINK_PERMISSIONS.REFERRALS_MANAGE,
    BLINK_PERMISSIONS.PROFILE_VIEW,
  ],
  [BLINK_ROLES.CAMPUS_AMBASSADOR]: [
    BLINK_PERMISSIONS.DASHBOARD_VIEW,
    BLINK_PERMISSIONS.PROFILE_VIEW,
  ],
}
